[package]
name = "course"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
eval = "0.4.3"

[[bin]]
name = "course"
#path = "01_variables.rs"
#path = "02_ownership.rs"
#path = "03_complex_types.rs"
#path = "04_flow_control.rs"
path = "05_match_pattern.rs"
